name: Minify and publish scripts

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.js'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
      
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/Jod'
      
      - name: Install Terser
        run: npm install -g terser
      
      - name: Minify
        run: |
          mkdir -p minified
          mkdir -p bookmarklets

          find src -name "*.js" -type f | while read -r file; do
            filename=$(basename "$file")

            basename_no_ext="${filename%.js}"
            minified_name="${basename_no_ext}.minified.js"

            terser "$file" -o "minified/$minified_name" --compress pure_funcs="['console.debug']"

            echo "javascript:$(cat "minified/$minified_name")" > "bookmarklets/${basename_no_ext}.txt"
          done
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: auto-minify scripts and generate bookmarklets"
          file_pattern: "minified/*.minified.js bookmarklets/*.txt"